spring:
  datasource:
    url: ${RDS_URL}
    driver-class-name: ${RDS_DRIVER}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
